version: '3.7'

services:
  nomad:
    image: multani/nomad
    command: agent -dev
    privileged: true
    network_mode: host
    # network_mode: bridge
    environment:
      NOMAD_LOCAL_CONFIG: |
        data_dir = "/nomad/data/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw