name: Setup Nomad
description: Setup Local Nomad cluster for use in GitHub Actions

runs:
  using: "composite"
  steps:
    - name: Start Nomad cluster in container
      run: |
        docker run -d \
          --name nomad-cluster \
          --privileged \
          --network host \
          -p 4646:4646 \
          -e NOMAD_LOCAL_CONFIG='data_dir = "/nomad/data/"' \
          -v /var/run/docker.sock:/var/run/docker.sock:rw \
          -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
          multani/nomad:latest \
          agent -dev
      shell: bash

    # Wait for Nomad to start by pinging port 4646
    - name: Wait for Nomad to be ready
      run: |
        for i in {1..10}; do
          if curl --silent --fail http://localhost:4646/v1/status/leader &> /dev/null; then
            echo "Nomad is ready"
            exit 0
          fi
          echo "Waiting for Nomad to be ready..."
          sleep 3
        done
        echo "Nomad did not start in time" >&2
        exit 1
      shell: bash
