name: noaas-go-ci

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19,1.20, 1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Setup Nomad
      uses: ./.github/actions/setup-nomad

    - name: Unit Tests
      run: make unit

    - name: CI
      run: make ci